- id: '1732061078437'
  name: 'Slaapkamer licht '
  entities:
    light.slaapkamer:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      supported_features: 0
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 6535
      color_temp: 153
      hs_color:
      - 54.768
      - 1.6
      rgb_color:
      - 255
      - 254
      - 250
      xy_color:
      - 0.326
      - 0.333
      friendly_name: 'slaapkamer '
      state: 'on'
  icon: mdi:alarm-light
  metadata: {}
