services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - TZ=Etc/UTC
      - WEBPASSWORD=3zKf5q2gW8
    volumes:
      - ./configs/pihole/etc-pihole:/etc/pihole
      - ./configs/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    # Expose DNS ports and also the web interface on a custom port (here 8082)
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8082:80"
    networks:
      - proxy_network

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Etc/UTC
    volumes:
      - ./configs/homeassistant:/config
    restart: unless-stopped
    ports:
      - "8123:8123"
    networks:
      - proxy_network

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./configs/qbittorrent/config:/config
      - ./media:/media
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - proxy_network

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./configs/sonarr/config:/config
      - ./media:/media
    restart: unless-stopped
    ports:
      - "8989:8989"
    networks:
      - proxy_network

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./configs/radarr/config:/config
      - ./media:/media
    restart: unless-stopped
    ports:
      - "7878:7878"
    networks:
      - proxy_network

  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./configs/readarr/config:/config
      - ./media:/media
    restart: unless-stopped
    ports:
      - "8787:8787"
    networks:
      - proxy_network

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    volumes:
      - ./configs/jellyfin/config:/config
      - ./cache/jellyfin/cache:/cache
      - ./media:/media
    restart: unless-stopped
    ports:
      - "8096:8096"
    networks:
      - proxy_network

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
    volumes:
      - ./configs/jellyseerr/config:/app/config
      - ./media:/media
    restart: unless-stopped
    ports:
      - "5055:5055"
    networks:
      - proxy_network

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./configs/prowlarr/config:/config
      - ./media:/media
    restart: unless-stopped
    ports:
      - "9696:9696"
    networks:
      - proxy_network

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    depends_on:
      - nextclouddb
      - redis
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis
    volumes:
      - ./cache/nextcloud/html:/var/www/html
      - ./configs/nextcloud/custom_apps:/var/www/html/custom_apps
      - ./configs/nextcloud/config:/var/www/html/config
      - ./data:/var/www/html/data
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - proxy_network

  nextclouddb:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - ./configs/nextclouddb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - proxy_network

  collabora:
    container_name: collabora
    image: collabora/code
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - password=password
      - username=nextcloud
      - domain=nextcloud.therobo.nl
      - extra_params=--o:ssl.enable=true
    restart: unless-stopped
    ports:
      - "9980:9980"
    networks:
      - proxy_network

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - ./configs/redis:/data
    restart: unless-stopped
    networks:
      - proxy_network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
